name: Scrape daily

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* 15 * * *"
  workflow_dispatch:


jobs:
  scrape:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout main
      uses: actions/checkout@v2
      with:
        path: main

    - name: checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: gh-pages
        ref: gh-pages

    - name: install
      run: pip install main/

    - name: scrape
      run: |
        mkdir _output
        coronamk-viber-scraper sync --infile gh-pages/messages.json --output _output/messages.json

    - name: push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_output
